---
- hosts: targets
  become: yes

  tasks:

    - name: Run cAdvisor container
      community.docker.docker_container:
        name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest

        state: started
        restart_policy: always

        ports:
          - "8085:8080"

        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:ro"
          - "/sys:/sys:ro"
          - "/var/lib/docker:/var/lib/docker:ro"
