---
- hosts: targets
  become: yes

  tasks:

    - name: Create nginx config directory
      file:
        path: /opt/nginx
        state: directory

    - name: Copy nginx config
      copy:
        src: nginx-config/default.conf
        dest: /opt/nginx/default.conf

    - name: Remove old nginx container
      community.docker.docker_container:
        name: nginx-container
        state: absent

    - name: Run nginx reverse proxy
      community.docker.docker_container:
        name: nginx-container
        image: nginx
        state: started
        restart_policy: always

        published_ports:
          - "80:80"

        volumes:
          - /opt/nginx/default.conf:/etc/nginx/conf.d/default.conf

        networks:
          - name: bridge

        extra_hosts:
          - host.docker.internal:host-gateway
