---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Python3 pip
  apt:
    name: python3-pip
    state: present

- name: Install Docker Python SDK
  pip:
    name: docker

- name: Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes
