services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - airbnb-network

  airbnb-app:
    image: jessemukesh/airbnb-app:latest
    container_name: airbnb-container

    depends_on:
      - postgres-db

    networks:
      - airbnb-network

  nginx:
    image: nginx:latest
    container_name: nginx-container

    depends_on:
      - airbnb-app

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - airbnb-network

networks:
  airbnb-network:

volumes:
  postgres-data:
